Issue #10 fix: Content Player - Avoid player reload during question switch
sunbird-content-plugins/org.ekstep.questionbank pull request #11
Opened 2018-07-06 07:30 UTC by gouravmore

Issue #10 fix: Content Player - Avoid player reload during question switch

2018-07-06 07:38 UTC, manojchandrashekar requested changes

2018-07-06 07:38 UTC, manojchandrashekar commented on editor/questionbankcontroller.js
> +      // document.getElementById("itemIframe").contentDocument.location.reload(true);
Remove commented code.

2018-07-06 07:38 UTC, manojchandrashekar commented on editor/questionbankcontroller.js
> +      itemIframe.contentWindow.initializePreview(configuration);
Have you tested this code? Where is the `itemIframe` defined?

2018-07-09 09:22 UTC, vinukumar-vs approved these changes

2018-07-09 09:23 UTC, merged