Issue #19 feat: Delete question option to be enabled
sunbird-content-plugins/org.ekstep.questionbank pull request #20
Opened 2018-07-20 09:30 UTC by AkshayaRathinavel

2018-07-26 10:11 UTC, manojchandrashekar requested changes

2018-07-26 10:11 UTC, manojchandrashekar commented on editor/questionbankcontroller.js
> +      $scope.assessmentId = questionObj.IL_UNIQUE_ID;
I don't remember using this reference before `questionObj.IL_UNIQUE_ID`. Is this the same as `questionObj.identifier`?

2018-07-26 10:11 UTC, manojchandrashekar commented on test/mocks/ediotor/eventListener-mock.js
> -windowmock.open = function(url, target, settings) {
The folder name is incorrect. Change it to `editor`.

2018-08-01 11:44 UTC, vinukumar-vs commented
https://project-sunbird.atlassian.net/browse/SB-4910
Scenarios are not updated in JIRA issue. Hence closing PR

2018-08-01 12:07 UTC, vinukumar-vs approved these changes

2018-08-01 12:07 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +    $scope.deleteQuestionHandler = function(questionObj) {
This logic has to improve. Too much code.

2018-08-01 12:10 UTC, vinukumar-vs approved these changes

2018-08-01 12:10 UTC, merged