Question copy
sunbird-content-plugins/org.ekstep.questionbank pull request #21
Opened 2018-07-22 18:43 UTC by JagadishPujari

2018-07-27 11:20 UTC, manojchandrashekar requested changes

2018-07-27 11:20 UTC, manojchandrashekar commented on editor/questionbankcontroller.js
> +      ecEditor.dispatchEvent('org.ekstep.editcontentmeta:showpopup', { action: 'question-filter-view', subType: 'questions', framework: "NCF", rootOrgId: ecEditor.getContext('channel'), type: 'conten
Why have you committed hard-coded values? Please verify your changes before you commit!

2018-07-27 11:20 UTC, manojchandrashekar commented on editor/questionbankcontroller.js
> +      ecEditor.dispatchEvent('org.ekstep.editcontentmeta:showpopup', { action: 'question-filter-view', subType: 'questions', framework: "NCF", rootOrgId: ecEditor.getContext('channel'), type: 'conten
Why have you committed hard-coded values? Please verify your changes before you commit!

2018-07-27 11:20 UTC, manojchandrashekar commented on package.json
> +        "gulp": "^3.9.1"
Why is this needed?

2018-07-27 11:20 UTC, manojchandrashekar commented on editor/questionbankcontroller.js
> +    $scope.copyQuestion = function(questionObj){
Why have you repeated the save question code here? Can't we make it a function and call it in both places?

2018-08-01 15:42 UTC, vinukumar-vs approved these changes

2018-08-01 15:43 UTC, merged