Question bank UI changes
sunbird-content-plugins/org.ekstep.questionbank pull request #27
Opened 2018-08-10 07:44 UTC by JagadishPujari

1. Question bank action buttons and title alignment.
2. Select(checkbox) on question preview should load.
3. Limit question title.

2018-08-13 06:24 UTC, vinukumar-vs requested changes

2018-08-13 06:24 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +      $scope.previewItem(selQuestion, true);
This is for what?

2018-08-13 06:24 UTC, vinukumar-vs commented on editor/questionbankmodal.html
> +                    <div class="header">{{ question.title | limitTo:100}}</div>
Why it is limiting to 100 characters. As i told, 2nd line should have ellipse at the end.

2018-08-13 06:24 UTC, vinukumar-vs commented on editor/style.css
> +    padding-top: 6px;
Why are you adding specific to only checkbox? What about copy & delete icon?

2018-08-13 10:32 UTC, JagadishPujari commented on editor/questionbankcontroller.js
> +      $scope.previewItem(selQuestion, true);
Play preview clicking on edit question.

2018-08-13 10:34 UTC, JagadishPujari commented on editor/style.css
> +    padding-top: 6px;
Checkbox always have some padding so its moving top so

2018-08-21 08:29 UTC, vinukumar-vs approved these changes

2018-08-21 08:35 UTC, merged