Issue #4 fix: css selector name with respective form id's
sunbird-content-plugins/org.ekstep.questionbank pull request #5
Opened 2018-06-12 13:08 UTC by JagadishPujari

2018-07-06 05:26 UTC, manojchandrashekar requested changes

2018-07-06 05:26 UTC, manojchandrashekar commented on editor/style.css
> +#filterMetaDataTemplate #content-meta-form{
@JagadishPujari Is this `id` correct? We had some confusion between `filterMetaDataTemplate` and `filterMetadataTemplate`, right?

2018-07-06 05:48 UTC, JagadishPujari commented on editor/style.css
> +#filterMetaDataTemplate #content-meta-form{
Yes, we changed into d-D (filterMetadataTemplate - filterMetaDataTemplate ).

2018-07-06 06:30 UTC, manojchandrashekar approved these changes

2018-07-06 06:30 UTC, manojchandrashekar commented
@vinukumar-vs FYA

2018-07-09 09:24 UTC, vinukumar-vs approved these changes

2018-07-09 09:24 UTC, merged