Topic filter
sunbird-content-plugins/org.ekstep.questionbank pull request #9
Opened 2018-07-03 06:21 UTC by AkshayaRathinavel

2018-07-06 05:34 UTC, manojchandrashekar commented
Merge https://github.com/sunbird-content-plugins/org.ekstep.questionbank/pull/7 before this.

2018-07-09 10:22 UTC, vinukumar-vs requested changes

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +      "topics_id": "org.ekstep.conceptselector"
For topic-selector, it should be "org.ekstep.topicselector". Chek it once again.

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +        if (data.key == "concepts") {
String comparison should should be always in lower-case.

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +          $scope.filterObj.topic = [];
Why the scope level variable name "topic"?

For concepts => $scope.filterObj.concepts then for topics it should be scope.filterObj.topics

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +          _.forEach(data.value, function(dataid) {
Please follow proper naming conventions. What is mean by dataid & dataid.identifier?

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +        $scope.searchQuestions($scope.filterObj);
Why are you passing scope level object(filterObj) as a function parameter? It can be accessed directly in any function within the same scope.

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +            case "topic":
It should be "topics", naming convention issue.

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +            PluginManager.pluginMap = org.ekstep.pluginframework.pluginManager.plugins;
Why are you writing this function as a scope level function? It should be handled by the plugin-framework itself.

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +          $scope.Totaltopics = data.length;
Naming convention issue. 
$scope.Totaltopics => $scope.totalTopics

2018-07-09 10:22 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +          $scope.Totaltopics = data.length;
Why dont you combine Concepts & topics related functions to a single function?

2018-07-17 14:52 UTC, vinukumar-vs approved these changes

2018-07-17 14:52 UTC, vinukumar-vs commented on editor/questionbankcontroller.js
> +        } else if (data.key == "topic") {
data.key.toLowerCase()

2018-07-17 14:52 UTC, merged